/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pioneer_PLocProvider_jni_jniNmeaDecoderIF */

#ifndef _Included_com_pioneer_PLocProvider_jni_jniNmeaDecoderIF
#define _Included_com_pioneer_PLocProvider_jni_jniNmeaDecoderIF
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pioneer_PLocProvider_jni_jniNmeaDecoderIF
 * Method:    SendCradleData
 * Signature: ([BI)V
 */
JNIEXPORT jboolean JNICALL Java_com_pioneer_cradle_PLocProvider_jni_jniNmeaDecoderIF_SendCradleData
  (JNIEnv *, jobject, jbyteArray, jint);



JNIEXPORT void JNICALL Java_com_pioneer_cradle_PLocProvider_jni_jniNmeaDecoderIF_getLocationInfo
  (JNIEnv *, jobject, jobject);


JNIEXPORT jobjectArray JNICALL Java_com_pioneer_cradle_PLocProvider_jni_jniNmeaDecoderIF_getSatelliteInfo
  (JNIEnv * env, jobject obj);

#ifdef __cplusplus
}
#endif
#endif
